const PORT = 4000;
const ONE_MINUTE = 60000;
const FIVE_MINUTES = ONE_MINUTE * 5;
const ONE_HOUR = ONE_MINUTE * 60;
// const TWENTY_FOUR_HOURS = ONE_HOUR * 24
const TWENTY_FOUR_HOURS = 86400000;

module.exports = {
  PORT,
  TWENTY_FOUR_HOURS,
  ONE_MINUTE,
  FIVE_MINUTES
};
